spring.application.name=backend

# 1. Configuración de la Conexión a la Base de Datos
spring.datasource.url=jdbc:postgresql://localhost:5432/life_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate / JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# 3. Monitoreo y Debugging (Muestra los queries en la terminal)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true